"""empty message

Revision ID: 120baa00da5a
Revises: b3bf2d69b415
Create Date: 2019-07-21 13:46:53.785532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '120baa00da5a'
down_revision = 'b3bf2d69b415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bicycles',
    sa.Column('user_Id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('num', sa.String(length=64), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('photo', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.String(length=64), nullable=True),
    sa.Column('handler', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('updatedate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_Id')
    )
    op.create_table('UserMsg',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_msg', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('bicycles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bicycles',
    sa.Column('UserId', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Num', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('Address', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Photo', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('City', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Detail', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Handler', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Status', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Updatedate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('UserId', name='bicycles_pkey')
    )
    op.drop_table('UserMsg')
    op.drop_table('Bicycles')
    # ### end Alembic commands ###
