"""empty message

Revision ID: 1e89c6a4014d
Revises: 120baa00da5a
Create Date: 2019-07-21 14:03:23.686151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e89c6a4014d'
down_revision = '120baa00da5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserMsg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserMsg',
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_msg', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='UserMsg_pkey')
    )
    # ### end Alembic commands ###
