"""empty message

Revision ID: 3aeeb016dd88
Revises: 252ea8b3521f
Create Date: 2019-06-29 10:47:06.629590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aeeb016dd88'
down_revision = '252ea8b3521f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bicycles',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.String(length=64), nullable=True),
    sa.Column('Name', sa.String(length=64), nullable=True),
    sa.Column('Num', sa.Integer(), nullable=True),
    sa.Column('Time', sa.TIMESTAMP(), nullable=True),
    sa.Column('Address', sa.String(length=64), nullable=True),
    sa.Column('Photo', sa.String(length=64), nullable=True),
    sa.Column('City', sa.String(length=64), nullable=True),
    sa.Column('Detail', sa.String(length=64), nullable=True),
    sa.Column('Handler', sa.String(length=64), nullable=True),
    sa.Column('Status', sa.String(length=64), nullable=True),
    sa.Column('Score', sa.Integer(), nullable=True),
    sa.Column('Updatedate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bicycles')
    # ### end Alembic commands ###
