"""empty message

Revision ID: 63ffcb66d88f
Revises: a0c35f0c98c1
Create Date: 2019-06-26 17:38:15.043206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ffcb66d88f'
down_revision = 'a0c35f0c98c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bicycles', sa.Column('Userid', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'Bicycles', ['Userid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Bicycles', type_='unique')
    op.drop_column('Bicycles', 'Userid')
    # ### end Alembic commands ###
