"""empty message

Revision ID: 6bf9e0867aab
Revises: f8428e9034f1
Create Date: 2019-07-25 21:09:26.510856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf9e0867aab'
down_revision = 'f8428e9034f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bicycles', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bicycles', 'level')
    # ### end Alembic commands ###
