"""empty message

Revision ID: 84cb700b5f32
Revises: 
Create Date: 2019-06-26 17:22:30.425177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84cb700b5f32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bicycles',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Userid', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=64), nullable=True),
    sa.Column('Num', sa.Integer(), nullable=True),
    sa.Column('Time', sa.TIMESTAMP(), nullable=True),
    sa.Column('Address', sa.String(length=64), nullable=True),
    sa.Column('Photo', sa.String(length=64), nullable=True),
    sa.Column('City', sa.String(length=64), nullable=True),
    sa.Column('Detail', sa.String(length=64), nullable=True),
    sa.Column('Handler', sa.String(length=64), nullable=True),
    sa.Column('Status', sa.String(length=64), nullable=True),
    sa.Column('Score', sa.Integer(), nullable=True),
    sa.Column('Updatedate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Userid')
    )
    op.drop_table('PictureDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PictureDate',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"PictureDate_Id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Uuid', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Title', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Description', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PictureDate_pkey'),
    sa.UniqueConstraint('Uuid', name='PictureDate_Uuid_key')
    )
    op.drop_table('Bicycles')
    # ### end Alembic commands ###
