"""empty message

Revision ID: a0c35f0c98c1
Revises: 84cb700b5f32
Create Date: 2019-06-26 17:36:53.451539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c35f0c98c1'
down_revision = '84cb700b5f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bicycles', sa.Column('UserId', sa.Integer(), nullable=False))
    op.drop_constraint('Bicycles_Userid_key', 'Bicycles', type_='unique')
    op.drop_column('Bicycles', 'Id')
    op.drop_column('Bicycles', 'Userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bicycles', sa.Column('Userid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Bicycles', sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"Bicycles_Id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.create_unique_constraint('Bicycles_Userid_key', 'Bicycles', ['Userid'])
    op.drop_column('Bicycles', 'UserId')
    # ### end Alembic commands ###
