"""empty message

Revision ID: adaa7107f2b8
Revises: ca54f7cfd944
Create Date: 2019-07-21 14:08:48.113708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adaa7107f2b8'
down_revision = 'ca54f7cfd944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bicycles',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('num', sa.String(length=64), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('photo', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.String(length=64), nullable=True),
    sa.Column('handler', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('updatedate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Bicycles')
    # ### end Alembic commands ###
