"""empty message

Revision ID: ca54f7cfd944
Revises: 1e89c6a4014d
Create Date: 2019-07-21 14:05:58.236991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca54f7cfd944'
down_revision = '1e89c6a4014d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bicycles', sa.Column('user_id', sa.String(length=64), nullable=False))
    op.drop_column('Bicycles', 'user_Id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bicycles', sa.Column('user_Id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('Bicycles', 'user_id')
    # ### end Alembic commands ###
