"""empty message

Revision ID: e3a5b9b74a9c
Revises: 3aeeb016dd88
Create Date: 2019-06-30 21:45:59.678595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a5b9b74a9c'
down_revision = '3aeeb016dd88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bicycles',
    sa.Column('UserId', sa.String(length=64), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=True),
    sa.Column('Num', sa.Integer(), nullable=True),
    sa.Column('Time', sa.TIMESTAMP(), nullable=True),
    sa.Column('Address', sa.String(length=64), nullable=True),
    sa.Column('Photo', sa.String(length=64), nullable=True),
    sa.Column('City', sa.String(length=64), nullable=True),
    sa.Column('Detail', sa.String(length=64), nullable=True),
    sa.Column('Handler', sa.String(length=64), nullable=True),
    sa.Column('Status', sa.String(length=64), nullable=True),
    sa.Column('Score', sa.Integer(), nullable=True),
    sa.Column('Updatedate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('UserId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bicycles')
    # ### end Alembic commands ###
