"""empty message

Revision ID: ec62d7ca28be
Revises: 6606140ee0bd
Create Date: 2019-08-07 18:19:53.337814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec62d7ca28be'
down_revision = '6606140ee0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'name')
    # ### end Alembic commands ###
